### PR TITLE
#2 Add New Monsters

### PR DESCRIPTION
**Pull request by pkmrs**
Add new monsters #2 
PES2UG21CS397
PREM KUMAR S

### CODE REVIEW

**Comment by pkmrs** [comment]
yo is preference given to the guy who uploaded earlier or not

**Comment by pkmrs** [comment]
bruh I legit uploaded before the other lady

**Comment by Himank101** [comment]
!bounty 25

**Comment by Himank101** [comment]
lessgoo! We now have two more emissaries of hell!!

**Pull request merged**
